export const environment = {
  production: true,
  worldskillsAppId: 800,
  worldskillsPeopleAppId: 600,
  worldskillsApi: 'https://api.worldskills.org',
  worldskillsApiAwards: 'https://api.worldskills.org/awards',
  worldskillsApiOrg: 'https://api.worldskills.org/org',
  worldskillsApiPeople: 'https://api.worldskills.org/people',
  worldskillsApiImages: 'https://api.worldskills.org/images',
  worldskillsClientId: '01f623251c02',
  worldskillsAuthorizeUrl: 'https://auth.worldskills.org/oauth/authorize',
  worldskillsAuthorizeRedirect: 'https://org.worldskills.org/',
  worldskillsAuthorizeUserinfoEndpoint: 'https://auth.worldskills.org/auth/users/loggedIn',
  worldskillsAuthUriPatterns: ['api.worldskills.org'],
};
