export const environment = {
  production: true,
  worldskillsAppId: 800,
  worldskillsPeopleAppId: 600,
  worldskillsAuthAppId: 300,
  worldskillsApi: 'https://api.worldskills.org',
  worldskillsApiAuth: 'https://api.worldskills.org/auth',
  worldskillsApiPeople: 'https://api.worldskills.org/people',
  worldskillsApiEvents: 'https://api.worldskills.org/events',
  worldskillsApiImages: 'https://api.worldskills.org/images',
  worldskillsApiResources: 'https://api.worldskills.org/resources',
  worldskillsClientId: '49775efbb906',
  worldskillsAuthorizeUrl: 'https://auth.worldskills.org/oauth/authorize',
  worldskillsAuthorizeRedirect: 'https://api.worldskills.org/',
  worldskillsAuthorizeUserinfoEndpoint: 'https://auth.worldskills.org/auth/users/loggedIn',
  worldskillsPuppeteer: 'https://api.worldskills.org/auth/sessions/operate_puppet',
  worldskillsAuthUriPatterns: ['api.worldskills.org'],
};
